### ISSUE TITLE
npm run serve启动，页面样式问题

### ISSUE THREAD

**Issue by zzx199313** [cookieY/Yearning-gemini#8]
首页：
![image](https://user-images.githubusercontent.com/40626806/108648672-ce7ce300-74f6-11eb-9d27-1c6125dfe6e0.png)
工单提交页：
![image](https://user-images.githubusercontent.com/40626806/108648690-d9d00e80-74f6-11eb-9f20-a7b891ab0234.png)
数据源添加页：
![image](https://user-images.githubusercontent.com/40626806/108648759-03893580-74f7-11eb-9e9f-49f2d6890b94.png)
还有其他页面，就不截图了。

**Comment by cookieY** [comment]
请将iview UI版本降级至4.4.0
